name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia 00:00 UTC
  workflow_dispatch:       # permite rodar manualmente
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: build snake svg
    runs-on: ubuntu-latest

    steps:
      - name: Gerar SVGs da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: Vini-ZL
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Publicar na branch `output`
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
